---
title: "Reflection Rubric"
format: 
  html: default
  docx: default
---

| Attribute     | Below Basic (1)                                                                                                                         | Basic (2)                                                                                                                                                                    | Proficient (3)                                                                                                                                                                                  | Advanced (4)                                                                                                                                                                        |
| ------------- | --------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Understanding | Reveals little understanding of the assigned artifact.                                                                                  | Reveals a questionable understanding of the assigned artifact and abstracts only a single significant piece of information as evidence.                                      | Reveals a relatively clear understanding of the assigned artifact and abstracts a couple of significant pieces of information as evidence.                                                      | Reveals a clear understanding of the assigned artifact and abstracts 3-5 significant pieces of information as evidence.                                                             |
| Quality       | Off-topic and does not provide significant evidence of reflective process.                                                              | Does not show evidence of reflection about the assigned artifact and its application to other course content; writing rarely reveals attempts at deeper levels of thinking.  | Shows some evidence of reflection about the assigned artifact and its application to other course content; writing usually reveals attempts at deeper levels of thinking.                       | Reveals clear and consistent evidence of reflection about the assigned artifact and its application to other course content; writing reveals attempts at deeper levels of thinking. |
| Quantity      | Significantly below the minimum word limit.                                                                                             | Somewhat below the minimum word limit.                                                                                                                                       | Meets the minimum word limit.                                                                                                                                                                   | Exceeds the minimum word limit.                                                                                                                                                     |
| Mechanics     | Writing style is in need of improvement; contains a significant number of errors in grammar, spelling, punctuation, and/or word choice. | Parts are relatively well written, but other parts reveal errors in grammar, spelling, punctuation, and/or word choice; clearly not carefully proofread prior to submission. | Generally well written, mostly incorporating accurate grammatical structure, spelling, punctuation, and word choice; proof artifact prior to submission could have caught the remaining errors. | Extremely well written, consistently incorporating accurate grammatical structure, spelling, punctuation, and word choice; clearly proofread and edited prior to submission.        |

: Modification of Rubric by Michael Lipscomb at the University of Minnesota
