project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "img/"
  output-dir: docs
  
website:
  title: "Using Statistics to Understand Engagement Patterns"
  description: "Homepage for STA 200 - Using Statistics to Understand Engagement Patterns"
  site-url: https://stats-tgeorge.github.io/STA364_TSApps/
  sidebar:
    background: "#BBBCBC"
    logo: "images/logo.png" # This is where I put my hex
    pinned: true
    align: center
    tools:
      - icon: bar-chart-line
        href: https://app.minitab.com
        text: "Minitab Online"
      - icon: person-fill
        text: "Moodle"
        menu:
          - text: Announcements
            url: https://moodle.cornellcollege.edu/mod/forum/view.php?id=329740
          - text: Gradebook
            url: https://moodle.cornellcollege.edu/grade/report/grader/index.php?id=8899
          - text: Homepage
            url: https://moodle.cornellcollege.edu/course/view.php?id=8899
      - icon: calendar-check-fill
        href: https://calendar.google.com/calendar/u/0?cid=Y180OGY2NzUzNDVmYWJiZGMxZDBhNzhiZGE5YjE0MTI4Yzg0ODQ5Yzc4ZjRlNzU5ODVhY2FhZWU5YThlYTE1YjVmQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20
        text: "Course Calendar"
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      # - section: "Course information"
      #   contents:
        - href: course-description.qmd
          text: Course Description
        - href: schedule.qmd
          text: Course Content Schedule
        - href: https://stats-tgeorge.github.io/personal_website/course-support.html
          text: Support
        - href: course-instructor.qmd
          text: Instructor Information
        # - href: project-description.qmd
        #   text: Project Description
        - href: course-syllabus.qmd
          text: Syllabus
        - href: course-links.qmd
          text: Useful Links
        - href: supplement.qmd
          text: Supplementary Documents
          
          
  page-footer:
    left: "Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}})"
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

  favicon: "/img/favicon.png"

execute:
  freeze: true


    

