---
title: "STA200 - Statistics for Social Justice"
subtitle: "Course Schedule and Due Dates"
---

+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date | Day | Materials and/or Activities                                                                                           | Homework (due at 8:30am the following day)                                                                                                                                                                                                                                           |
+======+=====+=======================================================================================================================+======================================================================================================================================================================================================================================================================================+
| 8/28 | 1   | [Activity 1](course-materials/activities/Activity1.qmd "Activity 1 - Why Investigate Inequity in Iowa?")              | Listen to podcast "[An Anti-Racist Approach to Data Science](https://statsandstories.net/society1/an-anti-racist-approach-to-data-science "https://statsandstories.net/society1/an-anti-racist-approach-to-data-science")" (25 minutes)                                              |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     |                                                                                                                       | Reflect on podcast. [Submit on Moodle](https://moodle.cornellcollege.edu/mod/assign/view.php?id=273424 "https://moodle.cornellcollege.edu/mod/assign/view.php?id=273424")                                                                                                            |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     |                                                                                                                       | [Pose a question for class discussion on Moodle](https://moodle.cornellcollege.edu/mod/forum/discuss.php?d=48568 "https://moodle.cornellcollege.edu/mod/forum/discuss.php?d=48568")                                                                                                  |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 8/29 | 2   | [Disparity Trap](https://disparitytrap.net/) board game and Activity (printed)                                        | Listen to podcast "[Why Black Women Are More Likely to Face Eviction](https://www.kqed.org/news/11905386/why-black-women-are-more-likely-to-face-eviction)" (35 minutes)                                                                                                             |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     |                                                                                                                       | Reflect on podcast. [Submit on Moodle](https://moodle.cornellcollege.edu/mod/assign/view.php?id=273528)                                                                                                                                                                              |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     |                                                                                                                       | [Post a question for class discussion on Moodle](https://moodle.cornellcollege.edu/mod/forum/discuss.php?d=48680 "https://moodle.cornellcollege.edu/mod/forum/discuss.php?d=48680")                                                                                                  |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     |                                                                                                                       | [Waypoint Volunteer Application](course-materials/documents/Waypoint%20Volunteer%20Application.pdf)- Submit on Moodle. Click [HERE](https://moodle.cornellcollege.edu/mod/assign/view.php?id=273570 "https://moodle.cornellcollege.edu/mod/assign/view.php?id=273570").              |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 8/30 | 3   | Waypoint and Iowa Legal Aid training's.                                                                               | Watch [Segregated by Design](https://www.segregatedbydesign.com/watch/ "You can slow the video in settings on bottom right.") video                                                                                                                                                  |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | [Activity 3](course-materials/activities/Activity3.qmd "Activity 3 - Using Waypoints Database")                       | Reflect on video. [Submit on Moodle](https://moodle.cornellcollege.edu/mod/assign/view.php?id=273640 "https://moodle.cornellcollege.edu/mod/assign/view.php?id=273640")                                                                                                              |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     |                                                                                                                       | [Post a question for class discussion on Moodle](https://moodle.cornellcollege.edu/mod/forum/discuss.php?d=48737 "https://moodle.cornellcollege.edu/mod/forum/discuss.php?d=48737")                                                                                                  |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 8/31 | 4   | Visit QRS.                                                                                                            | [OpenIntro](https://www.openintro.org/book/os/ "Free") Ch1 Exercises: 1.1, 1.4, 1.10, 1.11, 1.12, 1.25, 1.35, 1.40, 1.43                                                                                                                                                             |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | [OpenIntro Chapter 1 Notes](course-materials/slides/chp1.pdf)                                                         | Submit on paper.                                                                                                                                                                                                                                                                     |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/1  | 5   | [OpenIntro Chapter 2 Notes](course-materials/slides/chp2.pdf)                                                         | [OpenIntro](https://www.openintro.org/book/os/) Ch2 Exercises: 2.1, 2.2, 2.3, 2.4, 2.5, 2.7, 2.9, 2.10, 2.15, 2.16, 2.20, 2.21, 2.22, 2.23, 2.34                                                                                                                                     |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     |                                                                                                                       | Submit on paper.                                                                                                                                                                                                                                                                     |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/4  | 6   | [OpenIntro Data](https://www.openintro.org/data/)                                                                     | Listen to podcast "[Women's Homelessness in Canada: A gendered experience](https://crsp-talk.simplecast.com/episodes/womens-homelessness)" (76 minutes)                                                                                                                              |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | Ex: labor_market_discrimination and pop_race_2019                                                                     | [Post a question for class discussion on Moodle](https://moodle.cornellcollege.edu/mod/forum/discuss.php?d=48931 "https://moodle.cornellcollege.edu/mod/forum/discuss.php?d=48931")                                                                                                  |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | [IMS Ch6](https://openintro-ims.netlify.app/explore-applications "Intro to Modern Statistics Chapter 6")              |                                                                                                                                                                                                                                                                                      |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/5  | 7   | Group Project                                                                                                         | Reflect on panel event. [Submit on Moodle](https://moodle.cornellcollege.edu/mod/assign/view.php?id=274056 "https://moodle.cornellcollege.edu/mod/assign/view.php?id=274056")                                                                                                        |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | Housing Panel                                                                                                         |                                                                                                                                                                                                                                                                                      |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/6  | 8   | Group Project                                                                                                         | Reflect on lecture. [Submit on Moodle](https://moodle.cornellcollege.edu/mod/assign/view.php?id=274093 "https://moodle.cornellcollege.edu/mod/assign/view.php?id=274093")                                                                                                            |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | SYS Lecture                                                                                                           | Paired group project work.                                                                                                                                                                                                                                                           |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/7  | 9   | Group Project                                                                                                         | Reflect on [YAC](https://icalliances.org/ "Youth Action Council is part of the Institute of Community Alliances") youth visit. [Submit on Moodle](https://moodle.cornellcollege.edu/mod/assign/view.php?id=274094 "https://moodle.cornellcollege.edu/mod/assign/view.php?id=274094") |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | YAC Panel                                                                                                             | Paired group project work.                                                                                                                                                                                                                                                           |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/8  | 10  | Group Project                                                                                                         | Group Project                                                                                                                                                                                                                                                                        |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | Mid Block Presentations (Zoom)                                                                                        |                                                                                                                                                                                                                                                                                      |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/11 | 11  | Group Project                                                                                                         | Group Project                                                                                                                                                                                                                                                                        |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | Sign up for [Refugee Simulation](https://cmc-cr.org/welcoming-week/)                                                  |                                                                                                                                                                                                                                                                                      |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/12 | 12  | Group Project                                                                                                         | Refugee Simulation                                                                                                                                                                                                                                                                   |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | Evening Refugee Simulation (6:30-8:30).                                                                               | [Post a question for class discussion on Moodle](https://moodle.cornellcollege.edu/mod/forum/discuss.php?d=49241)                                                                                                                                                                    |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/13 | 13  | Group Project                                                                                                         | Work on [Analysis Report](project-description.qmd "Links to whole project description.")                                                                                                                                                                                             |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/14 | 14  | [Lead Me Home](https://www.leadmehomefilm.com/)                                                                       | [Lead Me Home Handout 3](course-materials/documents/Handout_Three.pdf "Part of Lead Me Home package of materials.") (handed out) [Source](https://www.leadmehomefilm.com/)                                                                                                           |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | [Handout One](course-materials/documents/Handout_One.pdf)                                                             | -   Link One: [A History of Homelessness In America](https://www.ncbi.nlm.nih.gov/books/NBK519584/?report=printable)                                                                                                                                                                 |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | [Handout Two](course-materials/documents/Handout_Two.pdf)                                                             | -   Link Two: [A Brief Timeline of Race and Homelessness in America](https://community.solutions/wp-content/uploads/2020/06/A-Brief-Timeline-of-Race-and-Homelessness-in-America-March-2019.pdf)                                                                                     |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | Group Project                                                                                                         | Finish [Analysis Report](project-description.qmd "Links to whole project description."), due at 11:59pm via [Moodle](https://moodle.cornellcollege.edu/mod/assign/view.php?id=274698)                                                                                                |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | [4 Approaches to Multiple-Race Questions](https://weallcount.com/2022/10/27/4-approaches-to-multiple-race-questions/) |                                                                                                                                                                                                                                                                                      |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/15 | 15  | Group Project                                                                                                         | Work on Group [Project Visual](project-description.qmd)                                                                                                                                                                                                                              |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | Project Visual In-Progress Meeting                                                                                    | [Lead Me Home Question Answers](course-materials/lead_me_home_questions_assignment.qmd "Links to assingment."). [Submit on Moodle](https://moodle.cornellcollege.edu/mod/assign/view.php?id=274945).                                                                                 |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/18 | 16  | Group Project Visual                                                                                                  | Finalize Group [Project Visual](project-description.qmd)                                                                                                                                                                                                                             |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | Practice Presentations using Visuals                                                                                  | [Submit visual file or files on Moodle](https://moodle.cornellcollege.edu/mod/assign/view.php?id=275018).                                                                                                                                                                            |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | Review of analysis report                                                                                             | Revise Analysis report.                                                                                                                                                                                                                                                              |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/19 | 17  | SYS Showcase                                                                                                          | Revise Analysis report                                                                                                                                                                                                                                                               |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     |                                                                                                                       | Fill out Group member survey on Moodle. [**Required.**]{.underline}                                                                                                                                                                                                                  |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9/20 | 18  | Present to Waypoint                                                                                                   | Revise Analysis report. Submit on [Moodle](https://moodle.cornellcollege.edu/mod/assign/view.php?id=274698) by 3pm                                                                                                                                                                   |
|      |     |                                                                                                                       |                                                                                                                                                                                                                                                                                      |
|      |     | Course Evaluations                                                                                                    | Fill out Waypoint feedback survey on [Moodle](https://cornellcollege.az1.qualtrics.com/jfe/form/SV_eEFktmb9QTw5YF0). Wait until after presentations.                                                                                                                                 |
+------+-----+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Course Google Calendar:

<https://calendar.google.com/calendar/u/0?cid=Y180OGY2NzUzNDVmYWJiZGMxZDBhNzhiZGE5YjE0MTI4Yzg0ODQ5Yzc4ZjRlNzU5ODVhY2FhZWU5YThlYTE1YjVmQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20>
