---
title: "Activity 1 - Why Investigate Inequity in Iowa?"
format: 
  html: default
  docx: default
---

Waypoint Services has tasked us to investigate a community service to help people who are houseless. Let's start by understanding inequity in housing.

[**Google Drive:**]{.underline} As part of the first activity, please create a shared Google Drive folder for your group this block and upload your .docx file to that folder. Once uploaded, you will all be able to work on that document at one time.

[**Roles:**]{.underline} In this activity, you will all be responsible for conducting searches and reviewing items found. Generally, you will all have assigned roles, but in this case, you should all be working on the shared document, adding different items as explained below. Please choose a facilitator.

Names\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Facilitator (make sure everybody is given space to share regularly)\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

1.  **No External Research** for this question. In your group, I would like you to discuss among yourselves how you would define inequity. Write a one-sentence definition.

2.  Now you can start to use the internet. Each group member should spend a few minutes looking for different definitions of inequity and examples. Each group member should select a different example. Consider looking for something you have a personal connection to or have thought about before. Include your examples below (make sure to cite your sources; websites are fine in this case).

3.  Now, as a group, decide on a single example of inequity. Give your definition below.

**Stop for class discussion.**

4.  Now that you have a definition for inequity, you can start to look for it in Iowa. In groups, please look for some anecdotal evidence. This type of evidence is primarily what Waypoint has founded their suspicions of inequity on. We are specifically looking for inequity in Iowa and how it relates to having a home.

    Start by talking among your group how you will search: what key words will you use? What do you consider are your likely sources? What is a quality source? How will you know if your search is thorough enough? There have been two natural disaster in Iowa in the last 20 years, a flood and a derecho, both of which destroyed many homes. Consider these events when conducting your search. Your goal is to

    Collect all of your search results into your shared document as you go along. Make sure you are taking notes on each sources so you remember why you included it. (make sure to cite your sources, websites are fine in this case)

    *Example of notes: "www.example.///." shows a video of those most affected by the derecho and features a person of color who is now homeless. They discuss how most of the that neighborhood are individual of color*

    Aim for at least 10 to 20 examples. You have a group for good reason.

5.  Create a presentation to be presented today on your findings. Use your examples to tell a story. You can use Powerpoint or other visualizing software but you are not required to. Make your presentation compelling and feel free to show off some of the most meaningful examples. All students must present some of your findings.
