---
title: "Day 2"
format: html
date: "26-August-2025"
Homework Due: August 27th at 9am
description: Homelessness
---

## Class Topics

-   *Lead me Home*

    -   Introduction
    -   Watch Lead me Home Documentary
    -   Lead Me Home [Handout 1](/course-materials/documents/Handout_One.pdf)
    -   Lead me Home [Folder for Readings](https://drive.google.com/drive/folders/1jlh-KrcQdtEBre07VXSJX0MkFm--cSay?usp=sharing)

-   SYS Showcase Information (15-20min, start at 10am)

-   Class discussion on Citizenship.

## Homework

-   Read Lead Me Home [Handout 2](/course-materials/documents/Handout_Two.pdf).

-   Complete a Round 2 reading from the folder at [THIS LINK](https://drive.google.com/drive/folders/1jlh-KrcQdtEBre07VXSJX0MkFm--cSay?usp=sharing). Then:

    -   Write a summary of the reading topic that relates to, is connected to, or has perpetuated homelessness today.

    -   Submit your summary at [THIS LINK](https://moodle.cornellcollege.edu/mod/assign/view.php?id=338101).

-   Lead Me Home [Handout 3](/course-materials/documents/Handout_Three.pdf), but submit your questions on the "Class Discussion Questions (Due Daily)" on Moodle at [THIS LINK](https://moodle.cornellcollege.edu/mod/forum/view.php?id=337610).

    -   Handout 3, link 1, [CLICK HERE](https://www.ncbi.nlm.nih.gov/books/NBK519584/)

    -   Handout 3, link 2, [CLICK HERE](https://community.solutions/wp-content/uploads/2020/06/A-Brief-Timeline-of-Race-and-Homelessness-in-America-March-2019.pdf)
