---
title: "Day 4"
format: html
date: "28-August-2025"
Homework Due: August 29th at 9am
description: Discussion, Projects, and OI 1.1-1.3
---

## Class Topics

-   Class discussion on "An Anti-Racist Approach to Data Science." (30 min)

-   OpenIntro Section 1.1- 1.3 (likely not all of it)

    -   Slides at [THIS LINK](/course-materials/slides/chapter1.html).

    -   Outline at [THIS LINK](/course-materials/slides/chapter1_o.html).

-   Group project overview (15 min)

-   [Activity 2](/course-materials/activities/Activity2.qmd)- Getting Started with Waypoint Data. [Google Doc](/course-materials/activities/Activity2.docx) for working.

## Homework

-   Listen to the podcast “[Why Black Women Are More Likely to Face Eviction](https://www.kqed.org/news/11905386/why-black-women-are-more-likely-to-face-eviction)” (35 minutes)
    -   Write a reflection and submit at [THIS LINK](https://moodle.cornellcollege.edu/mod/assign/view.php?id=338104). The reflection rubric can be seen at [THIS LINK](/course-materials/documents/reflectionrubric.qmd).

    -   Submit a question for class discussion [HERE](https://moodle.cornellcollege.edu/mod/forum/view.php?id=337610).
-   OI exercises: (start on page 11) 1.1, 1.2, 1.4, 1.8, 1.10, 1.12. Book available at [THIS LINK](https://leanpub.com/os). Submit in person.
